### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by wouterjsmit** [spoofax-shell-2017/spoofax-shell#2]
The REPL lacks syntax highlighting.

We require syntax highlighting that:
- [x] triggers as soon as the user starts typing a command
- [x] updated real-time

**Comment by justinvdk** [comment]
Triggers for changes to the text [here](https://github.com/spoofax-shell-2017/spoofax-shell/blob/develop/shell/org.metaborg.spoofax.shell.eclipse/src/main/java/org/metaborg/spoofax/shell/client/eclipse/impl/EclipseEditor.java#L142) for eclipse. Not sure how it performs if we update for every single character change.

**Comment by wouterjsmit** [comment]
>  Not sure how it performs if we update for every single character change.

I'm going to guess that the Eclipse reponse by itself should be timely enough, since highlighting works in the normal editor (for custom languages).
